server:
  port: 80
  #session失效时间最小一分钟
  session:
    timeout: 3600
spring:
  datasource:
    druid:
      url: jdbc:mysql://106.13.47.59:3306/guosecurity?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Bluewave1.
      driver-class-name: com.mysql.jdbc.Driver
      #连接池初始化大小最小最大
      initial-size: 2
      min-idle: 2
      max-active: 5
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #验证连接是否可用，使用的SQL语句
      validation-query: SELECT 1
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      #监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: guoadmin
        login-password: guoadmin
        #是否能按重制按键
        reset-enable: true

  #session存储类型
  session:
    store-type: redis
  jpa:
    show-sql: true
    #自动创建表结构
    generate-ddl: false
  #redis配置
  redis:
    host: 106.13.47.59
    port: 6379

#上传文件路径
uploadfiledir:
  filePath: /Users/shaohua/webapp/guoshsecurity

#是否开启swagger
sys:
  swagger:
    enable-swgger: true


guosh:
  security:
    #浏览器登陆配置
    browser:
      #loginPage: /demoLogin.html  #自定义登陆页面默认defaultLogin.html
      loginType: JSON  #JSON异步登陆 REDITECT同步登陆
      #rememberMeSeconds: 3600  #设置记住密码失效时间单位(秒)默认一小时
      #session:  #session配置
        #maximumSessions: 1 #用户最大session个数默认1
        #maxSessionsPreventsLogin: false #达到最大session时是否阻止新的登录请求，默认为false，不阻止
        #sessionInvalidUrl: session失效跳转路径
    #验证码相关配置
    code:
      #图形验证码配置属性:width,height,length,expreIn,url
      image:
        length: 4
      #短信验证码配置属性:length,expreIn,url
      sms:
        length: 6

    #第三方登陆
    social:
      #回调路径+供应商id等于第三方登录请求路径
      filtertProcessesUrl: /qqLogin
      qq:
        appId: 100550231
        appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
        #供应商id
        providerId: callback.do
      #微信登陆
      weixin:
        appId: wxd99431bbff8305a0
        appSecret: 60f78681d063590a469f1b297feff3c4
        #供应商id
        providerId: weixin