server:
  port: 8080
  context-path: /guoshsecurity

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/guosecurity?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      #连接池初始化大小最小最大
      initial-size: 2
      min-idle: 2
      max-active: 2
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #验证连接是否可用，使用的SQL语句
      validation-query: SELECT 1
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      #监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: guoadmin
        login-password: guoadmin
        #是否能按重制按键
        reset-enable: true
  #关闭spring session
  session:
    store-type: none
  jpa:
    show-sql: true
    #自动创建表结构
    generate-ddl: true

#先关闭security默认配置
#security:
#  basic:
#    enabled: false

#上传文件路径
uploadfiledir:
  filePath: /Users/shaohua/webapp/guoshsecurity

#是否开启swagger
sys:
  swagger:
    enable-swgger: true


guosh:
  security:
    browser:
      #自定义登陆页面
      #loginPage: /demoLogin.html
      #JSON异步登陆 REDITECT同步登陆
      loginType: JSON

    code:
      #image下面的属性有width,height,length,expreIn,url
      image:
        length: 5
        #url: /user/*